apiVersion: v1
kind: Service
metadata:
  name: loadbalance-svc
  namespace: production
  labels:
    app: appinfo
  annotations: {}
spec:
  type: LoadBalancer
  selector:
    app: appinfo
  ports:
    - name: http
      protocol: TCP
      port: 80  # Port to access service
      targetPort: 8080  # Port in the pod
