apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
  namespace: namespace
  labels:
    app: guestbook
data:
  NUMBER_OF_COMMENTS_PER_PAGE: "200"
  primary.cnf: |
    [mysqld]
    log-bin
    datadir=/var/lib/mysql/mysql  
