apiVersion: v1
kind: Pod
metadata:
  namespace: mostafa
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: nigelpoulton/getting-started-k8s:2.0
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 128Mi
        cpu: "0.5"